package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * About generated by hbm2java
 */
@Data
public class AboutReq  {
	
	private int aboutId;
	
	private String tittle;
	
	private String metaTittle;
	
	private String descriptions;
	
	private String details;
	
	private Date createdDate;
	
	private String createdBy;
	
	private Date modifiedDate;
	
	private String metaKeywords;
	
	private String metaDescription;

	public AboutReq() {
	}

	public AboutReq(int aboutId) {
		this.aboutId = aboutId;
	}

	public AboutReq(int aboutId, String tittle, String metaTittle, String descriptions, String details, Date createdDate,
			String createdBy, Date modifiedDate, String metaKeywords, String metaDescription) {
		this.aboutId = aboutId;
		this.tittle = tittle;
		this.metaTittle = metaTittle;
		this.descriptions = descriptions;
		this.details = details;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
	}

	
}
