package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * BillDetail generated by hbm2java
 */


@Data
public class BillDetailReq  {
	
	
	private int billDetailId;

	private Integer productId;
	
	private Integer billId;
	
	private Integer quantity;
	
	private Integer bdprice;

	public BillDetailReq() {
	}

	public BillDetailReq(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	public BillDetailReq(int billDetailId, Integer productId, Integer billId, Integer quantity, Integer bdprice) {
		this.billDetailId = billDetailId;
		this.productId = productId;
		this.billId = billId;
		this.quantity = quantity;
		this.bdprice = bdprice;
	}

	
}
