package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Customer generated by hbm2java
 */
@Data
public class CustomerReq  {
	
	private int customerId;
	
	private String customerName;
	
	private String address;
	
	private Integer phonenumber;

	public CustomerReq() {
	}

	public CustomerReq(int customerId) {
		this.customerId = customerId;
	}

	public CustomerReq(int customerId, String customerName, String address, Integer phonenumber) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.address = address;
		this.phonenumber = phonenumber;
	}

}
