package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ProductImage generated by hbm2java
 */
@Data
public class ImageReq  {

	private int ImageId;

	private String link;
	
	private Boolean main;

	public ImageReq() {
	}

	public ImageReq(int ImageId) {
		this.ImageId = ImageId;
	}

	public ImageReq(int ImageId, String link, Boolean main) {
		this.ImageId = ImageId;
		this.link = link;
		this.main = main;
	}

}
