package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Location generated by hbm2java
 */
@Data
public class LocationReq  {

	private Long locationId;
	
	private String locationName;
	
	private Date startTime;
	
	private Date endTime;
	
	private String description;

	public LocationReq() {
	}

	public LocationReq(String locationName) {
		this.locationName = locationName;
	}


}
