package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * NewTag generated by hbm2java
 */
@Data
public class NewTagReq {

	private int newTagID;
	
	private int newId;

	private int tagId;

	public NewTagReq() {
	}

	public NewTagReq(int newTagID) {
		this.newTagID = newTagID;
	}

	public NewTagReq(int newTagID,int newId, int tagId) {
		this.newTagID = newTagID;
		this.newId = newId;
		this.tagId = tagId;
	}

}
