package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ProductCategory generated by hbm2java
 */
@Data
public class ProductCategoryReq  {
	
	private int productCategoryID;

	private int productId;

	private int categoryId;

	private String nameCate;
	
	private String meataTittle;
	
	private Integer parrentId;
	
	private Integer displayOrder;
	
	private String seoTittle;
	
	private Date createdDate;
	
	private String createBy;
	
	private Date modifiedDate;
	
	private String metaKeywords;
	
	private String metaDescription;
	
	private Boolean statuss;
	
	private Boolean showOnHome;

	public ProductCategoryReq() {
	}

	public ProductCategoryReq(int categoryId) {
		this.categoryId = categoryId;
	}

	public ProductCategoryReq(int categoryId, String nameCate, String meataTittle, Integer parrentId, Integer displayOrder,
			String seoTittle, Date createdDate, String createBy, Date modifiedDate, String metaKeywords,
			String metaDescription, Boolean statuss, Boolean showOnHome) {
		this.categoryId = categoryId;
		this.nameCate = nameCate;
		this.meataTittle = meataTittle;
		this.parrentId = parrentId;
		this.displayOrder = displayOrder;
		this.seoTittle = seoTittle;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.statuss = statuss;
		this.showOnHome = showOnHome;
	}

}
