package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Roles generated by hbm2java
 */
@Data
public class RolesReq  {
	
	private int roleId;

	private String roleName;
	
	private String role;
	

	public RolesReq() {
	}

	public RolesReq(int roleId) {
		this.roleId = roleId;
	}

	public RolesReq(int roleId, String roleName, String role) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.role = role;
	}

}
