package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * RolePermission generated by hbm2java
 */

@Data
public class RolePermissionReq  {

	
	private int rolePermissionId;
	
	private int roleId;

	private int permissionId;
	
	private int actionActive;

	public RolePermissionReq() {
	}

	public RolePermissionReq(int rolePermissionId, int roleId, int permissionId, int actionActive) {
		this.rolePermissionId = rolePermissionId;
		this.roleId = roleId;
		this.permissionId = permissionId;
		this.actionActive = actionActive;
	}



}
