package com.hiep.doan.services.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Users generated by hbm2java
 */
@Data
public class UsersReq  {
	
	private int userId;
	
	private String password;

	private String username;

	public UsersReq() {
	}

	public UsersReq(int userId) {
		this.userId = userId;
	}

	public UsersReq(int userId, String password, String username) {
		this.userId = userId;
		this.password = password;
		this.username = username;
	}


}
