package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Actions generated by hbm2java
 */
@Entity
@Table(name = "Actions")
public class Actions implements java.io.Serializable {

	@Id
	@Column(name = "ActionId", nullable = false)
	private int actionId;
	@Column(name = "ActionCode")
	private String actionCode;
	@Column(name = "ActionName")
	private String actionName;

	public Actions() {
	}

	public Actions(int actionId) {
		this.actionId = actionId;
	}

	public Actions(int actionId, String actionCode, String actionName) {
		this.actionId = actionId;
		this.actionCode = actionCode;
		this.actionName = actionName;
	}

	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

}
