package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Actions generated by hbm2java
 */
@Data
@Entity
@Table(name = "Actions", schema = "dbo", catalog = "hiep")
public class Actions implements java.io.Serializable  {

	@Id
	@Column(name = "AboutId")
	private int actionId;
	
	@Basic
	@Column(name = "ActionCode")
	private String actionCode;
	
	@Basic
	@Column(name = "ActionName")
	private String actionName;

	public Actions() {
	}

	public Actions(int actionId) {
		this.actionId = actionId;
	}

	public Actions(int actionId, String actionCode, String actionName) {
		this.actionId = actionId;
		this.actionCode = actionCode;
		this.actionName = actionName;
	}

	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

}
