package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * BillDetail generated by hbm2java
 */

@Entity
@Table(name = "Bill", schema = "dbo", catalog = "hiep")
@Data
public class BillDetail implements java.io.Serializable {
	
	@Id
	@Column(name = "BillDetailId")
	private int billDetailId;
	@Id
	@Column(name = "ProductId")
	private Integer productId;
	
	@Id
	@Column(name = "BillId")
	private Integer billId;
	
	@Id
	@Column(name = "Quantity")
	private Integer quantity;
	
	@Id
	@Column(name = "Bdprice")
	private Integer bdprice;

	public BillDetail() {
	}

	public BillDetail(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	public BillDetail(int billDetailId, Integer productId, Integer billId, Integer quantity, Integer bdprice) {
		this.billDetailId = billDetailId;
		this.productId = productId;
		this.billId = billId;
		this.quantity = quantity;
		this.bdprice = bdprice;
	}

	public int getBillDetailId() {
		return this.billDetailId;
	}

	public void setBillDetailId(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getBdprice() {
		return this.bdprice;
	}

	public void setBdprice(Integer bdprice) {
		this.bdprice = bdprice;
	}

}
