package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Bill generated by hbm2java
 */
@Data
@Entity
@Table(name = "Bill", schema = "dbo", catalog = "hiep")
public class Bill implements java.io.Serializable  {
	
	@Id
	@Column(name = "BillId")
	private int billId;
	
	@Id
	@Column(name = "CreatedDate")
	private Date createdDate;
	
	@Id
	@Column(name = "CreateBy")
	private String createBy;
	
	@Id
	@Column(name = "ModifiedDate")
	private Date modifiedDate;
	
	@Id
	@Column(name = "DeliverId")
	private int deliverId;
	
	@Id
	@Column(name = "TotalPrice")
	private Integer totalPrice;
	
	@Id
	@Column(name = "CustomerId")
	private Integer customerId;

	public Bill() {
	}

	public Bill(int billId, int deliverId) {
		this.billId = billId;
		this.deliverId = deliverId;
	}

	public Bill(int billId, Date createdDate, String createBy, Date modifiedDate, int deliverId, Integer totalPrice,
			Integer customerId) {
		this.billId = billId;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.deliverId = deliverId;
		this.totalPrice = totalPrice;
		this.customerId = customerId;
	}

	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public int getDeliverId() {
		return this.deliverId;
	}

	public void setDeliverId(int deliverId) {
		this.deliverId = deliverId;
	}

	public Integer getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

}
