package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "Bill")
public class Bill implements java.io.Serializable {

	private int billId;
	private Date createdDate;
	private String createBy;
	private Date modifiedDate;
	private int deliverId;
	private Integer totalPrice;
	private Integer customerId;

	public Bill() {
	}

	public Bill(int billId, int deliverId) {
		this.billId = billId;
		this.deliverId = deliverId;
	}

	public Bill(int billId, Date createdDate, String createBy, Date modifiedDate, int deliverId, Integer totalPrice,
			Integer customerId) {
		this.billId = billId;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.deliverId = deliverId;
		this.totalPrice = totalPrice;
		this.customerId = customerId;
	}

	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public int getDeliverId() {
		return this.deliverId;
	}

	public void setDeliverId(int deliverId) {
		this.deliverId = deliverId;
	}

	public Integer getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

}
