package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "Image")
public class Image implements java.io.Serializable {

	@Id
	@Column(name = "ImageId", nullable = false)
	private int imageId;
	
	@Column(name = "Link")
	private String link;
	
	@Column(name = "Main")
	private Boolean main;

	public Image() {
	}

	public Image(int imageId) {
		this.imageId = imageId;
	}

	public Image(int imageId, String link, Boolean main) {
		this.imageId = imageId;
		this.link = link;
		this.main = main;
	}

	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}


	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Boolean getMain() {
		return this.main;
	}

	public void setMain(Boolean main) {
		this.main = main;
	}

}
