package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "Location")
public class Location implements java.io.Serializable {

	private int locationId;
	private String locationName;
	private Date startTime;
	private Date endTime;
	private String description;

	public Location() {
	}

	public Location(int locationId) {
		this.locationId = locationId;
	}

	public Location(int locationId, String locationName, Date startTime, Date endTime, String description) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.description = description;
	}

	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
