package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MenuType generated by hbm2java
 */
@Entity
@Table(name = "MenuType")
public class MenuType implements java.io.Serializable {
	@Id
	@Column(name = "menuTypeId", nullable = false)
	private int menuTypeId;
	
	@Column(name = "MenuName")
	private String menuName;

	public MenuType() {
	}

	public MenuType(int menuTypeId) {
		this.menuTypeId = menuTypeId;
	}

	public MenuType(int menuTypeId, String menuName) {
		this.menuTypeId = menuTypeId;
		this.menuName = menuName;
	}

	public int getMenuTypeId() {
		return this.menuTypeId;
	}

	public void setMenuTypeId(int menuTypeId) {
		this.menuTypeId = menuTypeId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

}
