package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * News generated by hbm2java
 */
@Data
@Entity
@Table(name = "News", schema = "dbo", catalog = "hiep")
public class News implements java.io.Serializable  {
	@Id
	@Column(name = "NewId")
	private int newId;
	@Basic
	@Column(name = "Tittle")
	private String tittle;
	@Basic
	@Column(name = "MetaTittle")
	private String metaTittle;
	@Basic
	@Column(name = "Descriptions")
	private String descriptions;
	@Basic
	@Column(name = "NewImage")
	private String newImage;
	@Basic
	@Column(name = "NewCategodyId")
	private Integer newCategodyId;
	@Basic
	@Column(name = "Detail")
	private String detail;
	@Basic
	@Column(name = "CreatedDate")
	private Date createdDate;
	@Basic
	@Column(name = "CreateBy")
	private String createBy;
	@Basic
	@Column(name = "ModifiedDate")
	private Date modifiedDate;
	@Basic
	@Column(name = "MetaKeywords")
	private String metaKeywords;
	@Basic
	@Column(name = "MetaDescription")
	private String metaDescription;
	@Basic
	@Column(name = "Statuss")
	private Boolean statuss;
	@Basic
	@Column(name = "TopHot")
	private Date topHot;
	@Basic
	@Column(name = "ViewCount")
	private Integer viewCount;
	@Basic
	@Column(name = "TagId")
	private String tagId;

	public News() {
	}

	public News(int newId) {
		this.newId = newId;
	}

	public News(int newId, String tittle, String metaTittle, String descriptions, String newImage,
			Integer newCategodyId, String detail, Date createdDate, String createBy, Date modifiedDate,
			String metaKeywords, String metaDescription, Boolean statuss, Date topHot, Integer viewCount,
			String tagId) {
		this.newId = newId;
		this.tittle = tittle;
		this.metaTittle = metaTittle;
		this.descriptions = descriptions;
		this.newImage = newImage;
		this.newCategodyId = newCategodyId;
		this.detail = detail;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.statuss = statuss;
		this.topHot = topHot;
		this.viewCount = viewCount;
		this.tagId = tagId;
	}

	public int getNewId() {
		return this.newId;
	}

	public void setNewId(int newId) {
		this.newId = newId;
	}

	public String getTittle() {
		return this.tittle;
	}

	public void setTittle(String tittle) {
		this.tittle = tittle;
	}

	public String getMetaTittle() {
		return this.metaTittle;
	}

	public void setMetaTittle(String metaTittle) {
		this.metaTittle = metaTittle;
	}

	public String getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	public String getNewImage() {
		return this.newImage;
	}

	public void setNewImage(String newImage) {
		this.newImage = newImage;
	}

	public Integer getNewCategodyId() {
		return this.newCategodyId;
	}

	public void setNewCategodyId(Integer newCategodyId) {
		this.newCategodyId = newCategodyId;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	public Boolean getStatuss() {
		return this.statuss;
	}

	public void setStatuss(Boolean statuss) {
		this.statuss = statuss;
	}

	public Date getTopHot() {
		return this.topHot;
	}

	public void setTopHot(Date topHot) {
		this.topHot = topHot;
	}

	public Integer getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

}
