package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NewTag generated by hbm2java
 */
@Entity
@Table(name = "NewTag")
public class NewTag implements java.io.Serializable {

	private int newTagId;
	private Integer newId;
	private Integer tagId;

	public NewTag() {
	}

	public NewTag(int newTagId) {
		this.newTagId = newTagId;
	}

	public NewTag(int newTagId, Integer newId, Integer tagId) {
		this.newTagId = newTagId;
		this.newId = newId;
		this.tagId = tagId;
	}

	public int getNewTagId() {
		return this.newTagId;
	}

	public void setNewTagId(int newTagId) {
		this.newTagId = newTagId;
	}

	public Integer getNewId() {
		return this.newId;
	}

	public void setNewId(Integer newId) {
		this.newId = newId;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

}
