package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "ProductImage")
@Data
public class ProductImage implements java.io.Serializable {

	
	@Id
	@Column(name = "ProductImageID", nullable = false)
	private int productImageID;

	@Column(name = "ImageID", nullable = false)
	private int imageID;

	
	@Column(name = "ProductId", nullable = false)
	private int productId;
	
	
}
