package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ProductLocation generated by hbm2java
 */
@Data
@Entity
@Table(name = "ActionActive", schema = "dbo", catalog = "hiep")
public class ProductLocation implements java.io.Serializable {
	@Id
	@Column(name = "LocationProductId")
	private int locationProductId;
	@Basic
	@Column(name = "LoctionId")
	private int loctionId;
	@Basic
	@Column(name = "ProdudctId")
	private int produdctId;

	public ProductLocation() {
	}

	public ProductLocation(int locationProductId, int loctionId, int produdctId) {
		this.locationProductId = locationProductId;
		this.loctionId = loctionId;
		this.produdctId = produdctId;
	}

	public int getLocationProductId() {
		return this.locationProductId;
	}

	public void setLocationProductId(int locationProductId) {
		this.locationProductId = locationProductId;
	}

	public int getLoctionId() {
		return this.loctionId;
	}

	public void setLoctionId(int loctionId) {
		this.loctionId = loctionId;
	}

	public int getProdudctId() {
		return this.produdctId;
	}

	public void setProdudctId(int produdctId) {
		this.produdctId = produdctId;
	}

}
