package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ProductImage generated by hbm2java
 */
@Data
@Entity
@Table(name = "ProductImage", schema = "dbo", catalog = "hiep")
public class ProductImage implements java.io.Serializable  {

	@Id
	@Column(name = "ProductImageId")
	private int productImageId;
	@Basic
	@Column(name = "Link")
	private String link;
	@Basic
	@Column(name = "Main")
	private Boolean main;

	public ProductImage() {
	}

	public ProductImage(int productImageId) {
		this.productImageId = productImageId;
	}

	public ProductImage(int productImageId, String link, Boolean main) {
		this.productImageId = productImageId;
		this.link = link;
		this.main = main;
	}

	public int getProductImageId() {
		return this.productImageId;
	}

	public void setProductImageId(int productImageId) {
		this.productImageId = productImageId;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Boolean getMain() {
		return this.main;
	}

	public void setMain(Boolean main) {
		this.main = main;
	}

}
