package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductLocation generated by hbm2java
 */
@Entity
@Table(name = "ProductLocation")
public class ProductLocation implements java.io.Serializable {

	private int locationProductId;
	private Integer loctionId;
	private Integer produdctId;

	public ProductLocation() {
	}

	public ProductLocation(int locationProductId) {
		this.locationProductId = locationProductId;
	}

	public ProductLocation(int locationProductId, Integer loctionId, Integer produdctId) {
		this.locationProductId = locationProductId;
		this.loctionId = loctionId;
		this.produdctId = produdctId;
	}

	public int getLocationProductId() {
		return this.locationProductId;
	}

	public void setLocationProductId(int locationProductId) {
		this.locationProductId = locationProductId;
	}

	public Integer getLoctionId() {
		return this.loctionId;
	}

	public void setLoctionId(Integer loctionId) {
		this.loctionId = loctionId;
	}

	public Integer getProdudctId() {
		return this.produdctId;
	}

	public void setProdudctId(Integer produdctId) {
		this.produdctId = produdctId;
	}

}
