package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product")
public class Product implements java.io.Serializable {

	private int productId;
	private String productCode;
	private String productName;
	private String metaTittle;
	private String descriptions;
	private Integer price;
	private Integer promotionPrice;
	private Integer quantity;
	private Integer categoryId;
	private String detail;
	private Date createdDate;
	private String createBy;
	private Date modifiedDate;
	private String metaKeywords;
	private String metaDescription;
	private Boolean statuss;
	private Date topHot;
	private Integer viewCount;
	private String locationBegin;
	private Integer productLocationId;
	private Integer combo;
	private Date timeStart;
	private Date timeEnd;

	public Product() {
	}

	public Product(int productId) {
		this.productId = productId;
	}

	public Product(int productId, String productCode, String productName, String metaTittle, String descriptions,
			Integer price, Integer promotionPrice, Integer quantity, Integer categoryId, String detail,
			Date createdDate, String createBy, Date modifiedDate, String metaKeywords, String metaDescription,
			Boolean statuss, Date topHot, Integer viewCount, String locationBegin, Integer productLocationId,
			Integer combo, Date timeStart, Date timeEnd) {
		this.productId = productId;
		this.productCode = productCode;
		this.productName = productName;
		this.metaTittle = metaTittle;
		this.descriptions = descriptions;
		this.price = price;
		this.promotionPrice = promotionPrice;
		this.quantity = quantity;
		this.categoryId = categoryId;
		this.detail = detail;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.statuss = statuss;
		this.topHot = topHot;
		this.viewCount = viewCount;
		this.locationBegin = locationBegin;
		this.productLocationId = productLocationId;
		this.combo = combo;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getMetaTittle() {
		return this.metaTittle;
	}

	public void setMetaTittle(String metaTittle) {
		this.metaTittle = metaTittle;
	}

	public String getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getPromotionPrice() {
		return this.promotionPrice;
	}

	public void setPromotionPrice(Integer promotionPrice) {
		this.promotionPrice = promotionPrice;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	public Boolean getStatuss() {
		return this.statuss;
	}

	public void setStatuss(Boolean statuss) {
		this.statuss = statuss;
	}

	public Date getTopHot() {
		return this.topHot;
	}

	public void setTopHot(Date topHot) {
		this.topHot = topHot;
	}

	public Integer getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	public String getLocationBegin() {
		return this.locationBegin;
	}

	public void setLocationBegin(String locationBegin) {
		this.locationBegin = locationBegin;
	}

	public Integer getProductLocationId() {
		return this.productLocationId;
	}

	public void setProductLocationId(Integer productLocationId) {
		this.productLocationId = productLocationId;
	}

	public Integer getCombo() {
		return this.combo;
	}

	public void setCombo(Integer combo) {
		this.combo = combo;
	}

	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

}
