package com.hiep.doan.services.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Roles generated by hbm2java
 */
@Data
@Entity
@Table(name = "Roles", schema = "dbo", catalog = "hiep")
public class Roles implements java.io.Serializable {
	@Id
	@Column(name = "RoleId")
	private int roleId;
	@Basic
	@Column(name = "RoleName")
	private String roleName;
	@Basic
	@Column(name = "Role")
	private String role;
	

	public Roles() {
	}

	public Roles(int roleId) {
		this.roleId = roleId;
	}

	public Roles(int roleId, String roleName, String role) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.role = role;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
