package com.hiep.doan.services.Entities;
// Generated May 25, 2020 3:40:20 PM by Hibernate Tools 5.4.7.Final

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "Tags")
public class Tags implements java.io.Serializable {

	private int tagId;
	private String tagName;

	public Tags() {
	}

	public Tags(int tagId) {
		this.tagId = tagId;
	}

	public Tags(int tagId, String tagName) {
		this.tagId = tagId;
		this.tagName = tagName;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

}
